PCOM = False
DBUG = True
PIPURL = ''
GBAD = "Timed-out on Google Data API. Sorry, try again."
numrows = 0
config = {}
html = ''
hobj = ''
row1 = []
nest = ''
mode = ''
letter = {1:'A',2:'B',3:'C',4:'D',5:'E',6:'F',7:'G',8:'H',9:'I',10:'J',11:'K'}
sheet = ''
modes = {'':''}
