#!/bin/bash

DAEMON=/usr/bin/python
ARGS=/var/pipulate/pipulate.py
PIDFILE=/var/run/serve.pid

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        --user www-data --group www-data \
        -b --make-pidfile \
        --chuid www-data \
        --exec $DAEMON $ARGS
    ;;
  stop)
    echo "Stopping server"
    # /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    /sbin/start-stop-daemon --stop --name python --verbose
    ;;
  *)
    echo "Usage: /etc/init.d/pipulate {start|stop}"
    exit 1
    ;;
esac

exit 0
